name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: |
          make release
          ls -la bin/

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: vidlogd-binaries
          path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: vidlogd-binaries
          path: bin/

      - name: List downloaded files
        run: ls -la bin/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/vidlogd-darwin-arm64
            bin/vidlogd-linux-amd64
            bin/vidlogd-windows-amd64.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 